title:   Kami's Braindump
copy:    2013 - 2016 Dominic Fandrey
url:     https://lonkamikaze.github.io
history: https://github.com/lonkamikaze/lonkamikaze.github.io/commits/master
code:    https://github.com/lonkamikaze/lonkamikaze.github.io/blob/master
style:
  date: "%F"
defaults:
- socope:
    path: ""
  values:
    name: "kamikaze/Dominic Fandrey"
    markdown: kramdown
    layout: default
- scope:
    path: ""
    type: "posts"
  values:
    author: "kami"
