title: Kami's Braindump
copy: 2013 - 2016 Dominic Fandrey
style:
  date: "%F"
defaults:
- socope:
    path: ""
  values:
    name: "kamikaze/Dominic Fandrey"
    markdown: kramdown
    layout: default
- scope:
    path: ""
    type: "posts"
  values:
    author: "kami"
